function [t,accx,accy,accz] = csv2acc(path)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here
%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/tillecki/Library/CloudStorage/OneDrive-Aarhusuniversitet/Master Electrical Engineering/Deep Learning/DeepL Project/Accelerometer/still.csv
%
% Auto-generated by MATLAB on 24-Nov-2023 12:25:08

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = [",", ";"];

% Specify column names and types
opts.VariableNames = ["time", "axms2", "ayms2", "azms2", "aTms2"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
%opts = setvaropts(opts, ["time", "axms2", "ayms2", "azms2", "aTms2"], "DecimalSeparator", ",");
%opts = setvaropts(opts, ["time", "axms2", "ayms2", "azms2", "aTms2"], "ThousandsSeparator", ".");

% Import the data
data = readtable(path,opts);

t = table2array(data(:,1));
accx = table2array(data(:,2));
accy = table2array(data(:,3));
accz = table2array(data(:,4));


end